---
title: "Biodiversity Assessment Tool (BdAT) for evaluating risks to wildlife populations from cumulative effects in the Oil Sands Region of Alberta, Canada"
author: "Andy Crosby, PhD"
#supervisor: 
site: bookdown::bookdown_site
output: 
  md_document:
    variant: gfm
    toc: TRUE
    toc_depth: 2
#bibliography: library.bib
#citation-style: ../../MendeleyBib/CitationStyles/nature.csl
#citation-style: https://www.zotero.org/styles/elsevier-harvard
documentclass: book
link-citations: true
github-repo: https://github.com/alberta-conservation/BdAT_shiny.git
description: "This is document explains the structure and use of the Biodiversity Assessment Tool."

---

# Overview


```{r GlobalOptions, echo=FALSE}
options(bookdown.render.file_scope = FALSE, knitr.duplicate.label = "allow") 
knitr::opts_chunk$set(cache.path = "5_cache/")
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{r setup, include=FALSE, cache=FALSE}
#Set root directory to R project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{r echo=FALSE, out.width = '100%'}
library(kableExtra)
library(knitr)
```




```{r child = 'Documentation/01_overview.Rmd'}
```


